providers:
  openai:
    enabled: true
    model: gpt-5.1-mini
    temperature: 0.2
    max_output_tokens: 600
    timeout_seconds: 15
  twitter:
    enabled: false
    base_url: "https://api.twitter.com/2"
    recent_search_endpoint: "/tweets/search/recent"
    query: "(SOL OR Solana) (DEX OR DeFi) -is:retweet lang:en"
    max_results: 25
    lookback_minutes: 90

research_policy:
  universe: ["SOL", "JUP", "ORCA"]
  constraints: "Spot only, keine Leverage"
  risk_bounds: [1, 5]
  ttl_minutes_default: 90
  stop_loss_pct: 1.5
  take_profit_pct: 2.0

routing:
  prefer_openai: true
  use_twitter_signals: false

logging:
  level: "INFO"
  write_idea_reports: true
  report_dir: "Report"

env:
  OPENAI_API_KEY: "${OPENAI_API_KEY}"
  X_BEARER_TOKEN: "${X_BEARER_TOKEN}"